// Auth
export const SIGNING_IN = "SIGNING_IN";
export const SIGNED_IN = "SIGNED_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_ERR = "AUTH_ERR";

// Stream
export const CREATED_STREAM = "CREATED_STREAM";
export const FETCHING_STREAM = "FETCHING_STREAM";
export const FETCHED_STREAM = "FETCHED_STREAM";
export const FETCHING_FAILED_STREAM = "FETCHING_FAILED_STREAM";
export const NOT_FOUND_STREAM = "NOT_FOUND_STREAM";

export const FETCHING_FAILED_STREAMS = "FETCHING_FAILED_STREAMS";
export const FETCHING_STREAMS = "FETCHING_STREAMS";
export const FETCHED_STREAMS = "FETCHED_STREAMS";
